# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\eclipse mares programs\eric6\dataproject\InquiryWindowSdudent.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(888, 572)
        TabWidget.setMinimumSize(QtCore.QSize(0, 0))
        TabWidget.setMaximumSize(QtCore.QSize(1366, 800))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        TabWidget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/hλlf-life.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        TabWidget.setToolTip("")
        TabWidget.setStyleSheet("background-color: rgb(150, 150, 150);\n"
"")
        TabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        TabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        TabWidget.setIconSize(QtCore.QSize(16, 16))
        self.equipment = QtWidgets.QWidget()
        self.equipment.setObjectName("equipment")
        self.TWeqpmNum = QtWidgets.QTableWidget(self.equipment)
        self.TWeqpmNum.setGeometry(QtCore.QRect(30, 50, 481, 231))
        self.TWeqpmNum.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.TWeqpmNum.setStyleSheet("\n"
"background-color: rgb(235, 255, 253);")
        self.TWeqpmNum.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.TWeqpmNum.setWordWrap(True)
        self.TWeqpmNum.setRowCount(10)
        self.TWeqpmNum.setColumnCount(2)
        self.TWeqpmNum.setObjectName("TWeqpmNum")
        item = QtWidgets.QTableWidgetItem()
        self.TWeqpmNum.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWeqpmNum.setHorizontalHeaderItem(1, item)
        self.TWeqpmNum.horizontalHeader().setCascadingSectionResizes(True)
        self.TWeqpmNum.horizontalHeader().setHighlightSections(True)
        self.TWeqpmNum.horizontalHeader().setMinimumSectionSize(50)
        self.TWeqpmNum.horizontalHeader().setStretchLastSection(True)
        self.TWeqpmNum.verticalHeader().setVisible(False)
        self.TWeqpmNum.verticalHeader().setCascadingSectionResizes(True)
        self.TWeqpmNum.verticalHeader().setSortIndicatorShown(True)
        self.TWeqpmNum.verticalHeader().setStretchLastSection(True)
        self.PBInquire = QtWidgets.QPushButton(self.equipment)
        self.PBInquire.setGeometry(QtCore.QRect(410, 340, 75, 44))
        self.PBInquire.setMinimumSize(QtCore.QSize(0, 44))
        self.PBInquire.setToolTip("")
        self.PBInquire.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBInquire.setObjectName("PBInquire")
        self.label_4 = QtWidgets.QLabel(self.equipment)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.label_4.setStyleSheet("font: 12pt \"仿宋\";")
        self.label_4.setObjectName("label_4")
        self.LBrand = QtWidgets.QLabel(self.equipment)
        self.LBrand.setGeometry(QtCore.QRect(540, 80, 331, 121))
        self.LBrand.setText("")
        self.LBrand.setPixmap(QtGui.QPixmap("image/gamersky_06origin_11_20161017926842.png"))
        self.LBrand.setObjectName("LBrand")
        self.LFacilityImage = QtWidgets.QLabel(self.equipment)
        self.LFacilityImage.setGeometry(QtCore.QRect(540, 290, 321, 151))
        self.LFacilityImage.setText("")
        self.LFacilityImage.setPixmap(QtGui.QPixmap("image/gamersky_07origin_13_20161017926EFB.png"))
        self.LFacilityImage.setObjectName("LFacilityImage")
        self.layoutWidget = QtWidgets.QWidget(self.equipment)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 460, 365, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setSpacing(42)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PBReadme = QtWidgets.QPushButton(self.layoutWidget)
        self.PBReadme.setMinimumSize(QtCore.QSize(0, 40))
        self.PBReadme.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBReadme.setObjectName("PBReadme")
        self.horizontalLayout_7.addWidget(self.PBReadme)
        self.PBRecord = QtWidgets.QPushButton(self.layoutWidget)
        self.PBRecord.setMinimumSize(QtCore.QSize(0, 40))
        self.PBRecord.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBRecord.setObjectName("PBRecord")
        self.horizontalLayout_7.addWidget(self.PBRecord)
        self.PBDmgRec = QtWidgets.QPushButton(self.layoutWidget)
        self.PBDmgRec.setMinimumSize(QtCore.QSize(0, 40))
        self.PBDmgRec.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBDmgRec.setObjectName("PBDmgRec")
        self.horizontalLayout_7.addWidget(self.PBDmgRec)
        self.layoutWidget1 = QtWidgets.QWidget(self.equipment)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 330, 347, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setSpacing(19)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.CBCampus = QtWidgets.QComboBox(self.layoutWidget1)
        self.CBCampus.setStyleSheet("background-color: rgb(235, 255, 253);")
        self.CBCampus.setObjectName("CBCampus")
        self.verticalLayout_3.addWidget(self.CBCampus)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setWhatsThis("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.LECatagory = QtWidgets.QLineEdit(self.layoutWidget1)
        self.LECatagory.setObjectName("LECatagory")
        self.verticalLayout_4.addWidget(self.LECatagory)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.LNeqpmNum = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.LNeqpmNum.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.LNeqpmNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LNeqpmNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LNeqpmNum.setDigitCount(5)
        self.LNeqpmNum.setObjectName("LNeqpmNum")
        self.verticalLayout_5.addWidget(self.LNeqpmNum)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.PBRefresh = QtWidgets.QPushButton(self.equipment)
        self.PBRefresh.setGeometry(QtCore.QRect(410, 390, 75, 23))
        self.PBRefresh.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBRefresh.setObjectName("PBRefresh")
        TabWidget.addTab(self.equipment, "")
        self.area = QtWidgets.QWidget()
        self.area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.area.setObjectName("area")
        self.TWCourtUseRecord = QtWidgets.QTableWidget(self.area)
        self.TWCourtUseRecord.setGeometry(QtCore.QRect(40, 60, 510, 171))
        self.TWCourtUseRecord.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TWCourtUseRecord.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.TWCourtUseRecord.setAcceptDrops(False)
        self.TWCourtUseRecord.setAutoFillBackground(False)
        self.TWCourtUseRecord.setStyleSheet("background-color: rgb(235, 255, 253);")
        self.TWCourtUseRecord.setIconSize(QtCore.QSize(0, 0))
        self.TWCourtUseRecord.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.TWCourtUseRecord.setWordWrap(True)
        self.TWCourtUseRecord.setRowCount(10)
        self.TWCourtUseRecord.setColumnCount(2)
        self.TWCourtUseRecord.setObjectName("TWCourtUseRecord")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        item.setFont(font)
        self.TWCourtUseRecord.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        item.setFont(font)
        self.TWCourtUseRecord.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtUseRecord.setItem(9, 1, item)
        self.TWCourtUseRecord.horizontalHeader().setCascadingSectionResizes(True)
        self.TWCourtUseRecord.horizontalHeader().setDefaultSectionSize(252)
        self.TWCourtUseRecord.horizontalHeader().setHighlightSections(True)
        self.TWCourtUseRecord.horizontalHeader().setMinimumSectionSize(50)
        self.TWCourtUseRecord.horizontalHeader().setStretchLastSection(True)
        self.TWCourtUseRecord.verticalHeader().setVisible(False)
        self.TWCourtUseRecord.verticalHeader().setCascadingSectionResizes(True)
        self.TWCourtUseRecord.verticalHeader().setSortIndicatorShown(True)
        self.TWCourtUseRecord.verticalHeader().setStretchLastSection(True)
        self.label_6 = QtWidgets.QLabel(self.area)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.label_6.setStyleSheet("font: 12pt \"仿宋\";")
        self.label_6.setObjectName("label_6")
        self.PBReadme_2 = QtWidgets.QPushButton(self.area)
        self.PBReadme_2.setGeometry(QtCore.QRect(150, 470, 80, 40))
        self.PBReadme_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBReadme_2.setObjectName("PBReadme_2")
        self.PBRecord_2 = QtWidgets.QPushButton(self.area)
        self.PBRecord_2.setGeometry(QtCore.QRect(300, 470, 100, 40))
        self.PBRecord_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBRecord_2.setObjectName("PBRecord_2")
        self.LCourtImage = QtWidgets.QLabel(self.area)
        self.LCourtImage.setGeometry(QtCore.QRect(580, 270, 281, 251))
        self.LCourtImage.setText("")
        self.LCourtImage.setPixmap(QtGui.QPixmap("image/gamersky_08origin_15_20165743577C.png"))
        self.LCourtImage.setObjectName("LCourtImage")
        self.LGPSLocation = QtWidgets.QLabel(self.area)
        self.LGPSLocation.setGeometry(QtCore.QRect(580, 70, 291, 171))
        self.LGPSLocation.setText("")
        self.LGPSLocation.setPixmap(QtGui.QPixmap("image/gamersky_02origin_03_20167111714E4E.png"))
        self.LGPSLocation.setObjectName("LGPSLocation")
        self.layoutWidget2 = QtWidgets.QWidget(self.area)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 280, 547, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.CBCourt = QtWidgets.QComboBox(self.layoutWidget2)
        self.CBCourt.setMinimumSize(QtCore.QSize(0, 20))
        self.CBCourt.setStyleSheet("background-color: rgb(235, 255, 253);")
        self.CBCourt.setObjectName("CBCourt")
        self.horizontalLayout.addWidget(self.CBCourt)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.CBCampus_2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.CBCampus_2.setMinimumSize(QtCore.QSize(0, 20))
        self.CBCampus_2.setStyleSheet("background-color: rgb(235, 255, 253);")
        self.CBCampus_2.setObjectName("CBCampus_2")
        self.horizontalLayout.addWidget(self.CBCampus_2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.CBCourtNum = QtWidgets.QComboBox(self.layoutWidget2)
        self.CBCourtNum.setMinimumSize(QtCore.QSize(0, 20))
        self.CBCourtNum.setStyleSheet("background-color: rgb(235, 255, 253);")
        self.CBCourtNum.setObjectName("CBCourtNum")
        self.horizontalLayout.addWidget(self.CBCourtNum)
        self.PBDetailedInfo = QtWidgets.QPushButton(self.layoutWidget2)
        self.PBDetailedInfo.setMinimumSize(QtCore.QSize(0, 20))
        self.PBDetailedInfo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBDetailedInfo.setObjectName("PBDetailedInfo")
        self.horizontalLayout.addWidget(self.PBDetailedInfo)
        self.PBRefresh_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.PBRefresh_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBRefresh_2.setObjectName("PBRefresh_2")
        self.horizontalLayout.addWidget(self.PBRefresh_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget3 = QtWidgets.QWidget(self.area)
        self.layoutWidget3.setGeometry(QtCore.QRect(50, 379, 485, 54))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setEnabled(True)
        self.label_3.setWhatsThis("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DTEStartTime = QtWidgets.QDateTimeEdit(self.layoutWidget3)
        self.DTEStartTime.setToolTipDuration(0)
        self.DTEStartTime.setWrapping(False)
        self.DTEStartTime.setMaximumDate(QtCore.QDate(2017, 12, 31))
        self.DTEStartTime.setMinimumDate(QtCore.QDate(2016, 11, 12))
        self.DTEStartTime.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.DTEStartTime.setCalendarPopup(True)
        self.DTEStartTime.setTimeSpec(QtCore.Qt.LocalTime)
        self.DTEStartTime.setObjectName("DTEStartTime")
        self.horizontalLayout_3.addWidget(self.DTEStartTime)
        self.TEStartHour = QtWidgets.QTimeEdit(self.layoutWidget3)
        self.TEStartHour.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.TEStartHour.setObjectName("TEStartHour")
        self.horizontalLayout_3.addWidget(self.TEStartHour)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setEnabled(True)
        self.label_8.setWhatsThis("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DTEStopTime = QtWidgets.QDateTimeEdit(self.layoutWidget3)
        self.DTEStopTime.setWrapping(False)
        self.DTEStopTime.setMaximumDate(QtCore.QDate(2017, 12, 31))
        self.DTEStopTime.setMinimumDate(QtCore.QDate(2016, 11, 12))
        self.DTEStopTime.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.DTEStopTime.setCalendarPopup(True)
        self.DTEStopTime.setTimeSpec(QtCore.Qt.LocalTime)
        self.DTEStopTime.setObjectName("DTEStopTime")
        self.horizontalLayout_4.addWidget(self.DTEStopTime)
        self.TEEndHour = QtWidgets.QTimeEdit(self.layoutWidget3)
        self.TEEndHour.setObjectName("TEEndHour")
        self.horizontalLayout_4.addWidget(self.TEEndHour)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.PBConfirmReservation = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBConfirmReservation.sizePolicy().hasHeightForWidth())
        self.PBConfirmReservation.setSizePolicy(sizePolicy)
        self.PBConfirmReservation.setMinimumSize(QtCore.QSize(0, 45))
        self.PBConfirmReservation.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(168, 168, 168, 255), stop:0.98 rgba(153, 221, 255, 255), stop:1 rgba(0, 0, 0, 0));")
        self.PBConfirmReservation.setObjectName("PBConfirmReservation")
        self.horizontalLayout_6.addWidget(self.PBConfirmReservation)
        self.label_6.raise_()
        self.PBReadme_2.raise_()
        self.PBRecord_2.raise_()
        self.LCourtImage.raise_()
        self.LGPSLocation.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.TWCourtUseRecord.raise_()
        TabWidget.addTab(self.area, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "查询"))
        self.TWeqpmNum.setSortingEnabled(True)
        item = self.TWeqpmNum.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "种类"))
        item = self.TWeqpmNum.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "数量"))
        self.PBInquire.setText(_translate("TabWidget", "查询"))
        self.label_4.setText(_translate("TabWidget", "快速浏览："))
        self.PBReadme.setText(_translate("TabWidget", "用户须知"))
        self.PBRecord.setText(_translate("TabWidget", "借订记录"))
        self.PBDmgRec.setText(_translate("TabWidget", "损坏记录"))
        self.label_5.setText(_translate("TabWidget", "校区："))
        self.label.setText(_translate("TabWidget", "输入器材种类："))
        self.label_2.setText(_translate("TabWidget", "当前可用数量："))
        self.PBRefresh.setText(_translate("TabWidget", "刷新信息"))
        TabWidget.setTabText(TabWidget.indexOf(self.equipment), _translate("TabWidget", "器材"))
        self.area.setToolTip(_translate("TabWidget", "<html><head/><body><p><br/></p></body></html>"))
        self.TWCourtUseRecord.setSortingEnabled(True)
        item = self.TWCourtUseRecord.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "开始时间"))
        item = self.TWCourtUseRecord.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "结束时间"))
        __sortingEnabled = self.TWCourtUseRecord.isSortingEnabled()
        self.TWCourtUseRecord.setSortingEnabled(False)
        self.TWCourtUseRecord.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("TabWidget", "预定记录浏览："))
        self.PBReadme_2.setText(_translate("TabWidget", "用户须知"))
        self.PBRecord_2.setText(_translate("TabWidget", "个人预定记录"))
        self.label_7.setText(_translate("TabWidget", "场地："))
        self.label_10.setText(_translate("TabWidget", "校区："))
        self.label_9.setText(_translate("TabWidget", "编号："))
        self.PBDetailedInfo.setText(_translate("TabWidget", "详细信息"))
        self.PBRefresh_2.setText(_translate("TabWidget", "刷新信息"))
        self.label_3.setText(_translate("TabWidget", "选择开始时间(小时)："))
        self.DTEStartTime.setDisplayFormat(_translate("TabWidget", "yyyy/M/d"))
        self.TEStartHour.setDisplayFormat(_translate("TabWidget", "H:00"))
        self.label_8.setText(_translate("TabWidget", "选择结束时间(小时)："))
        self.DTEStopTime.setDisplayFormat(_translate("TabWidget", "yyyy/M/d"))
        self.TEEndHour.setDisplayFormat(_translate("TabWidget", "H:00"))
        self.PBConfirmReservation.setText(_translate("TabWidget", "确认预定"))
        TabWidget.setTabText(TabWidget.indexOf(self.area), _translate("TabWidget", "场地"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

