# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\eclipse mares programs\eric6\dataproject\ManagerInterface.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(827, 475)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/hλlf-life.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        TabWidget.setStyleSheet("background-color: rgb(255, 249, 237);\n"
"")
        TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        TabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        TabWidget.setElideMode(QtCore.Qt.ElideNone)
        TabWidget.setDocumentMode(False)
        TabWidget.setTabsClosable(False)
        TabWidget.setMovable(False)
        TabWidget.setTabBarAutoHide(False)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(600, 30, 171, 401))
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 167, 267))
        self.page.setObjectName("page")
        self.LECommunicate = QtWidgets.QLineEdit(self.page)
        self.LECommunicate.setGeometry(QtCore.QRect(20, 134, 133, 20))
        self.LECommunicate.setObjectName("LECommunicate")
        self.SBQuantity = QtWidgets.QSpinBox(self.page)
        self.SBQuantity.setGeometry(QtCore.QRect(20, 90, 40, 20))
        self.SBQuantity.setObjectName("SBQuantity")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 72, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(20, 28, 51, 16))
        self.label_6.setObjectName("label_6")
        self.LEUser = QtWidgets.QLineEdit(self.page)
        self.LEUser.setGeometry(QtCore.QRect(20, 46, 133, 20))
        self.LEUser.setObjectName("LEUser")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(20, 116, 71, 16))
        self.label_8.setObjectName("label_8")
        self.PBLendEquip = QtWidgets.QPushButton(self.page)
        self.PBLendEquip.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.PBLendEquip.setObjectName("PBLendEquip")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 167, 267))
        self.page_2.setObjectName("page_2")
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setGeometry(QtCore.QRect(20, 42, 51, 16))
        self.label_33.setObjectName("label_33")
        self.LEUser_2 = QtWidgets.QLineEdit(self.page_2)
        self.LEUser_2.setGeometry(QtCore.QRect(20, 60, 133, 20))
        self.LEUser_2.setObjectName("LEUser_2")
        self.PBSeeRecord = QtWidgets.QPushButton(self.page_2)
        self.PBSeeRecord.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.PBSeeRecord.setObjectName("PBSeeRecord")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 167, 267))
        self.page_3.setObjectName("page_3")
        self.widget_2 = QtWidgets.QWidget(self.page_3)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 151, 209))
        self.widget_2.setObjectName("widget_2")
        self.LEEquipName = QtWidgets.QLineEdit(self.widget_2)
        self.LEEquipName.setGeometry(QtCore.QRect(11, 33, 129, 19))
        self.LEEquipName.setObjectName("LEEquipName")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(11, 11, 45, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(11, 107, 30, 16))
        self.label_12.setObjectName("label_12")
        self.CBSupplier = QtWidgets.QComboBox(self.widget_2)
        self.CBSupplier.setGeometry(QtCore.QRect(11, 81, 129, 19))
        self.CBSupplier.setObjectName("CBSupplier")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(11, 155, 30, 16))
        self.label_13.setObjectName("label_13")
        self.DSBPrice = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.DSBPrice.setGeometry(QtCore.QRect(11, 129, 129, 19))
        self.DSBPrice.setMaximum(100000.0)
        self.DSBPrice.setObjectName("DSBPrice")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(11, 59, 45, 16))
        self.label_11.setObjectName("label_11")
        self.PBConfirmAdd = QtWidgets.QPushButton(self.widget_2)
        self.PBConfirmAdd.setGeometry(QtCore.QRect(72, 174, 68, 23))
        self.PBConfirmAdd.setStyleSheet("")
        self.PBConfirmAdd.setObjectName("PBConfirmAdd")
        self.SBQuantity_2 = QtWidgets.QSpinBox(self.widget_2)
        self.SBQuantity_2.setGeometry(QtCore.QRect(11, 177, 54, 19))
        self.SBQuantity_2.setMaximum(200)
        self.SBQuantity_2.setObjectName("SBQuantity_2")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 167, 267))
        self.page_4.setObjectName("page_4")
        self.widget = QtWidgets.QWidget(self.page_4)
        self.widget.setGeometry(QtCore.QRect(0, 0, 161, 191))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 144, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.LERespPerson = QtWidgets.QLineEdit(self.layoutWidget)
        self.LERespPerson.setObjectName("LERespPerson")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.LERespPerson)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.CBEquipName = QtWidgets.QComboBox(self.layoutWidget)
        self.CBEquipName.setObjectName("CBEquipName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CBEquipName)
        self.SBQuantity_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.SBQuantity_3.setObjectName("SBQuantity_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SBQuantity_3)
        self.PBConfirmBroke = QtWidgets.QPushButton(self.widget)
        self.PBConfirmBroke.setGeometry(QtCore.QRect(30, 140, 100, 23))
        self.PBConfirmBroke.setObjectName("PBConfirmBroke")
        self.PBDelBorkRec = QtWidgets.QPushButton(self.widget)
        self.PBDelBorkRec.setGeometry(QtCore.QRect(30, 165, 100, 23))
        self.PBDelBorkRec.setMinimumSize(QtCore.QSize(0, 21))
        self.PBDelBorkRec.setObjectName("PBDelBorkRec")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 167, 267))
        self.page_5.setObjectName("page_5")
        self.widget_3 = QtWidgets.QWidget(self.page_5)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 151, 147))
        self.widget_3.setObjectName("widget_3")
        self.LESupplierName = QtWidgets.QLineEdit(self.widget_3)
        self.LESupplierName.setGeometry(QtCore.QRect(9, 36, 133, 20))
        self.LESupplierName.setObjectName("LESupplierName")
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        self.label_21.setGeometry(QtCore.QRect(9, 9, 71, 16))
        self.label_21.setObjectName("label_21")
        self.LECommunicate_2 = QtWidgets.QLineEdit(self.widget_3)
        self.LECommunicate_2.setGeometry(QtCore.QRect(9, 89, 133, 20))
        self.LECommunicate_2.setObjectName("LECommunicate_2")
        self.label_26 = QtWidgets.QLabel(self.widget_3)
        self.label_26.setGeometry(QtCore.QRect(9, 62, 71, 16))
        self.label_26.setObjectName("label_26")
        self.PBConfirmAddSupplier = QtWidgets.QPushButton(self.widget_3)
        self.PBConfirmAddSupplier.setGeometry(QtCore.QRect(9, 115, 75, 23))
        self.PBConfirmAddSupplier.setObjectName("PBConfirmAddSupplier")
        self.toolBox.addItem(self.page_5, "")
        self.tabWidget = QtWidgets.QTabWidget(self.tab)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 551, 381))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.TWUseOverview = QtWidgets.QTableWidget(self.tab_4)
        self.TWUseOverview.setGeometry(QtCore.QRect(20, 50, 511, 291))
        self.TWUseOverview.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWUseOverview.setObjectName("TWUseOverview")
        self.TWUseOverview.setColumnCount(5)
        self.TWUseOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWUseOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWUseOverview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWUseOverview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWUseOverview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWUseOverview.setHorizontalHeaderItem(4, item)
        self.TWUseOverview.horizontalHeader().setDefaultSectionSize(120)
        self.TWUseOverview.horizontalHeader().setMinimumSectionSize(30)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.TWEquipOverview = QtWidgets.QTableWidget(self.tab_5)
        self.TWEquipOverview.setGeometry(QtCore.QRect(10, 50, 261, 291))
        self.TWEquipOverview.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWEquipOverview.setObjectName("TWEquipOverview")
        self.TWEquipOverview.setColumnCount(2)
        self.TWEquipOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWEquipOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWEquipOverview.setHorizontalHeaderItem(1, item)
        self.LCDRemain = QtWidgets.QLCDNumber(self.tab_5)
        self.LCDRemain.setGeometry(QtCore.QRect(340, 10, 64, 23))
        self.LCDRemain.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.LCDRemain.setObjectName("LCDRemain")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(152, 10, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(276, 10, 61, 16))
        self.label_5.setObjectName("label_5")
        self.CBEquipment = QtWidgets.QComboBox(self.tab_5)
        self.CBEquipment.setGeometry(QtCore.QRect(189, 11, 81, 20))
        self.CBEquipment.setObjectName("CBEquipment")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(280, 60, 241, 281))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("image/4a7eadff9b551651ab47592dd7c07dcd.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.TWBreakOverview = QtWidgets.QTableWidget(self.tab_3)
        self.TWBreakOverview.setGeometry(QtCore.QRect(20, 50, 511, 291))
        self.TWBreakOverview.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWBreakOverview.setObjectName("TWBreakOverview")
        self.TWBreakOverview.setColumnCount(5)
        self.TWBreakOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWBreakOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWBreakOverview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWBreakOverview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWBreakOverview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWBreakOverview.setHorizontalHeaderItem(4, item)
        self.TWBreakOverview.horizontalHeader().setDefaultSectionSize(120)
        self.TWBreakOverview.horizontalHeader().setMinimumSectionSize(30)
        self.tabWidget.addTab(self.tab_3, "")
        self.PBRefresh = QtWidgets.QPushButton(self.tab)
        self.PBRefresh.setGeometry(QtCore.QRect(480, 30, 75, 23))
        self.PBRefresh.setObjectName("PBRefresh")
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab1)
        self.toolBox_2.setGeometry(QtCore.QRect(600, 30, 191, 361))
        self.toolBox_2.setStyleSheet("")
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 191, 257))
        self.page_6.setObjectName("page_6")
        self.label = QtWidgets.QLabel(self.page_6)
        self.label.setGeometry(QtCore.QRect(20, 11, 31, 20))
        self.label.setObjectName("label")
        self.CBCourt = QtWidgets.QComboBox(self.page_6)
        self.CBCourt.setGeometry(QtCore.QRect(63, 11, 81, 20))
        self.CBCourt.setObjectName("CBCourt")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(10, 63, 51, 16))
        self.label_3.setObjectName("label_3")
        self.PBConfirm = QtWidgets.QPushButton(self.page_6)
        self.PBConfirm.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.PBConfirm.setObjectName("PBConfirm")
        self.label_32 = QtWidgets.QLabel(self.page_6)
        self.label_32.setGeometry(QtCore.QRect(10, 37, 51, 20))
        self.label_32.setObjectName("label_32")
        self.CBCourtNum = QtWidgets.QComboBox(self.page_6)
        self.CBCourtNum.setGeometry(QtCore.QRect(63, 37, 81, 20))
        self.CBCourtNum.setObjectName("CBCourtNum")
        self.CBServer = QtWidgets.QComboBox(self.page_6)
        self.CBServer.setGeometry(QtCore.QRect(63, 63, 81, 20))
        self.CBServer.setObjectName("CBServer")
        self.DEStart = QtWidgets.QDateEdit(self.page_6)
        self.DEStart.setGeometry(QtCore.QRect(30, 120, 110, 22))
        self.DEStart.setDate(QtCore.QDate(2016, 11, 29))
        self.DEStart.setObjectName("DEStart")
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 31, 16))
        self.label_2.setObjectName("label_2")
        self.DEEnd = QtWidgets.QDateEdit(self.page_6)
        self.DEEnd.setGeometry(QtCore.QRect(30, 160, 110, 22))
        self.DEEnd.setDate(QtCore.QDate(2016, 11, 29))
        self.DEEnd.setObjectName("DEEnd")
        self.PBEnd = QtWidgets.QPushButton(self.page_6)
        self.PBEnd.setGeometry(QtCore.QRect(50, 218, 75, 23))
        self.PBEnd.setObjectName("PBEnd")
        self.toolBox_2.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_7.setObjectName("page_7")
        self.widget_4 = QtWidgets.QWidget(self.page_7)
        self.widget_4.setGeometry(QtCore.QRect(-10, 10, 181, 231))
        self.widget_4.setObjectName("widget_4")
        self.LECourtType = QtWidgets.QLineEdit(self.widget_4)
        self.LECourtType.setGeometry(QtCore.QRect(20, 90, 133, 20))
        self.LECourtType.setObjectName("LECourtType")
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        self.label_24.setGeometry(QtCore.QRect(20, 58, 71, 16))
        self.label_24.setObjectName("label_24")
        self.PBConfirm_2 = QtWidgets.QPushButton(self.widget_4)
        self.PBConfirm_2.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.PBConfirm_2.setObjectName("PBConfirm_2")
        self.toolBox_2.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_8.setObjectName("page_8")
        self.widget_7 = QtWidgets.QWidget(self.page_8)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 161, 211))
        self.widget_7.setObjectName("widget_7")
        self.splitter_3 = QtWidgets.QSplitter(self.widget_7)
        self.splitter_3.setGeometry(QtCore.QRect(20, 130, 111, 61))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit.setObjectName("lineEdit")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.PBValid = QtWidgets.QPushButton(self.splitter_2)
        self.PBValid.setObjectName("PBValid")
        self.PBInvalid = QtWidgets.QPushButton(self.splitter_2)
        self.PBInvalid.setObjectName("PBInvalid")
        self.splitter_4 = QtWidgets.QSplitter(self.widget_7)
        self.splitter_4.setGeometry(QtCore.QRect(20, 20, 111, 91))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_36 = QtWidgets.QLabel(self.splitter_4)
        self.label_36.setObjectName("label_36")
        self.CBCourtType = QtWidgets.QComboBox(self.splitter_4)
        self.CBCourtType.setObjectName("CBCourtType")
        self.label_22 = QtWidgets.QLabel(self.splitter_4)
        self.label_22.setObjectName("label_22")
        self.CBCourtNum_2 = QtWidgets.QComboBox(self.splitter_4)
        self.CBCourtNum_2.setObjectName("CBCourtNum_2")
        self.toolBox_2.addItem(self.page_8, "")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_12.setObjectName("page_12")
        self.widget_6 = QtWidgets.QWidget(self.page_12)
        self.widget_6.setGeometry(QtCore.QRect(10, 0, 157, 141))
        self.widget_6.setObjectName("widget_6")
        self.label_28 = QtWidgets.QLabel(self.widget_6)
        self.label_28.setGeometry(QtCore.QRect(10, 18, 71, 16))
        self.label_28.setObjectName("label_28")
        self.LEBuilderName = QtWidgets.QLineEdit(self.widget_6)
        self.LEBuilderName.setGeometry(QtCore.QRect(10, 36, 133, 20))
        self.LEBuilderName.setObjectName("LEBuilderName")
        self.LEBuilderCommunicate = QtWidgets.QLineEdit(self.widget_6)
        self.LEBuilderCommunicate.setGeometry(QtCore.QRect(10, 80, 133, 20))
        self.LEBuilderCommunicate.setObjectName("LEBuilderCommunicate")
        self.label_29 = QtWidgets.QLabel(self.widget_6)
        self.label_29.setGeometry(QtCore.QRect(10, 62, 81, 16))
        self.label_29.setObjectName("label_29")
        self.PBConfirm_4 = QtWidgets.QPushButton(self.widget_6)
        self.PBConfirm_4.setGeometry(QtCore.QRect(10, 106, 75, 23))
        self.PBConfirm_4.setObjectName("PBConfirm_4")
        self.toolBox_2.addItem(self.page_12, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab1)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 50, 551, 351))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.TWCourtOverView = QtWidgets.QTableWidget(self.tab_7)
        self.TWCourtOverView.setGeometry(QtCore.QRect(10, 30, 521, 281))
        self.TWCourtOverView.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWCourtOverView.setColumnCount(4)
        self.TWCourtOverView.setObjectName("TWCourtOverView")
        self.TWCourtOverView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtOverView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtOverView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtOverView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWCourtOverView.setHorizontalHeaderItem(3, item)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.TWResvOverview = QtWidgets.QTableWidget(self.tab_2)
        self.TWResvOverview.setGeometry(QtCore.QRect(10, 30, 521, 281))
        self.TWResvOverview.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWResvOverview.setColumnCount(5)
        self.TWResvOverview.setObjectName("TWResvOverview")
        self.TWResvOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWResvOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWResvOverview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWResvOverview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWResvOverview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWResvOverview.setHorizontalHeaderItem(4, item)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.TWServOverview = QtWidgets.QTableWidget(self.tab_6)
        self.TWServOverview.setGeometry(QtCore.QRect(10, 30, 521, 281))
        self.TWServOverview.setStyleSheet("background-image: url(:/添加/image/back.jpg);")
        self.TWServOverview.setColumnCount(6)
        self.TWServOverview.setObjectName("TWServOverview")
        self.TWServOverview.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TWServOverview.setHorizontalHeaderItem(5, item)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.PBRefresh_2 = QtWidgets.QPushButton(self.tab1)
        self.PBRefresh_2.setGeometry(QtCore.QRect(490, 30, 75, 23))
        self.PBRefresh_2.setObjectName("PBRefresh_2")
        TabWidget.addTab(self.tab1, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "管理员"))
        self.label_7.setText(_translate("TabWidget", "数量"))
        self.label_6.setText(_translate("TabWidget", "用户号"))
        self.label_8.setText(_translate("TabWidget", "联系方式"))
        self.PBLendEquip.setText(_translate("TabWidget", "借出器材"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("TabWidget", "借出器材"))
        self.label_33.setText(_translate("TabWidget", "用户号"))
        self.PBSeeRecord.setText(_translate("TabWidget", "查看记录"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("TabWidget", "归还器材"))
        self.label_10.setText(_translate("TabWidget", "器材名"))
        self.label_12.setText(_translate("TabWidget", "单价"))
        self.label_13.setText(_translate("TabWidget", "数量"))
        self.label_11.setText(_translate("TabWidget", "供应商"))
        self.PBConfirmAdd.setText(_translate("TabWidget", "确认"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("TabWidget", "器材增加"))
        self.label_30.setText(_translate("TabWidget", "责任人"))
        self.label_16.setText(_translate("TabWidget", " 器材名"))
        self.label_17.setText(_translate("TabWidget", "数量"))
        self.PBConfirmBroke.setText(_translate("TabWidget", "确认"))
        self.PBDelBorkRec.setText(_translate("TabWidget", "删除损坏记录"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("TabWidget", "器材损坏"))
        self.label_21.setText(_translate("TabWidget", "供应商名"))
        self.label_26.setText(_translate("TabWidget", "联系方式"))
        self.PBConfirmAddSupplier.setText(_translate("TabWidget", "确认"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("TabWidget", "添加供应商"))
        item = self.TWUseOverview.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "种类"))
        item = self.TWUseOverview.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "数量"))
        item = self.TWUseOverview.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "账号"))
        item = self.TWUseOverview.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "姓名"))
        item = self.TWUseOverview.horizontalHeaderItem(4)
        item.setText(_translate("TabWidget", "联系方式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("TabWidget", "使用信息"))
        item = self.TWEquipOverview.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "器材名"))
        item = self.TWEquipOverview.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "可用数量"))
        self.label_4.setText(_translate("TabWidget", "器材"))
        self.label_5.setText(_translate("TabWidget", "剩余数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("TabWidget", "器材总览"))
        item = self.TWBreakOverview.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "种类"))
        item = self.TWBreakOverview.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "数量"))
        item = self.TWBreakOverview.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "账号"))
        item = self.TWBreakOverview.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "姓名"))
        item = self.TWBreakOverview.horizontalHeaderItem(4)
        item.setText(_translate("TabWidget", "联系方式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TabWidget", "器材损坏总览"))
        self.PBRefresh.setText(_translate("TabWidget", "刷新纪录"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "器材"))
        self.label.setText(_translate("TabWidget", "场地"))
        self.label_3.setText(_translate("TabWidget", "维护商"))
        self.PBConfirm.setText(_translate("TabWidget", "确定报修"))
        self.label_32.setText(_translate("TabWidget", "场地号"))
        self.label_2.setText(_translate("TabWidget", "时间"))
        self.PBEnd.setText(_translate("TabWidget", "结束报修"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("TabWidget", "场地报修"))
        self.label_24.setText(_translate("TabWidget", "场地种类"))
        self.PBConfirm_2.setText(_translate("TabWidget", "确认"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("TabWidget", "场地添加"))
        self.PBValid.setText(_translate("TabWidget", "可用"))
        self.PBInvalid.setText(_translate("TabWidget", "不可用"))
        self.label_36.setText(_translate("TabWidget", "场地类型"))
        self.label_22.setText(_translate("TabWidget", "场地号"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), _translate("TabWidget", "场地可用状态"))
        self.label_28.setText(_translate("TabWidget", "承建商名"))
        self.label_29.setText(_translate("TabWidget", "联系方式"))
        self.PBConfirm_4.setText(_translate("TabWidget", "确认"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_12), _translate("TabWidget", "添加维护商"))
        item = self.TWCourtOverView.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "编号"))
        item = self.TWCourtOverView.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "类型"))
        item = self.TWCourtOverView.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "校区"))
        item = self.TWCourtOverView.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "可用状态"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("TabWidget", "场地总览"))
        item = self.TWResvOverview.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "场地"))
        item = self.TWResvOverview.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "起讫时间"))
        item = self.TWResvOverview.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "预定账户"))
        item = self.TWResvOverview.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "用户姓名"))
        item = self.TWResvOverview.horizontalHeaderItem(4)
        item.setText(_translate("TabWidget", "联系方式"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("TabWidget", "预定信息"))
        item = self.TWServOverview.horizontalHeaderItem(0)
        item.setText(_translate("TabWidget", "编号"))
        item = self.TWServOverview.horizontalHeaderItem(1)
        item.setText(_translate("TabWidget", "类型"))
        item = self.TWServOverview.horizontalHeaderItem(2)
        item.setText(_translate("TabWidget", "开始时间"))
        item = self.TWServOverview.horizontalHeaderItem(3)
        item.setText(_translate("TabWidget", "结束时间"))
        item = self.TWServOverview.horizontalHeaderItem(4)
        item.setText(_translate("TabWidget", "维护商"))
        item = self.TWServOverview.horizontalHeaderItem(5)
        item.setText(_translate("TabWidget", "联系方式"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("TabWidget", "维护状态"))
        self.PBRefresh_2.setText(_translate("TabWidget", "刷新信息"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "场地"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

